# Generated by Django 4.2.16 on 2024-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='apply_fuzzylogic',
            field=models.BooleanField(default=False),
        ),
    ]
