# Generated by Django 4.2.16 on 2024-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_types_apply_fuzzylogic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='qc_paased',
            field=models.BooleanField(default=False),
        ),
    ]
