# Generated by Django 5.1.1 on 2024-10-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_quizsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='selected_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
