# Generated by Django 4.2.16 on 2024-11-22 13:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_topics_delete_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLesson',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('audio_content', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('video_content', models.FileField(blank=True, null=True, upload_to='video/')),
                ('display_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('delete_flag', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_lessons', to='quizapp.topics')),
            ],
            options={
                'verbose_name_plural': 'Topic Lessons',
            },
        ),
    ]
